# This is a basic workflow to help you get started with Actions

name: Update

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup vhs repository
        run: |
          mkdir -p /etc/apt/keyrings
          curl -fsSL https://repo.charm.sh/apt/gpg.key | gpg --dearmor -o /etc/apt/keyrings/charm.gpg
          echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | tee /etc/apt/sources.list.d/charm.list

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: vhs ffmpeg
          version: 1.0

      - name: Cleanup
        run: rm renders/*.gif && rm tapes/*.tape

      - name: Update Tapes
        run: ruby tape_updater.rb

      - name: Run VHS
        run: for i in ./tapes/*.tape; do vhs "$i"; done

      - name: Update README.md
        run: ruby readme_updater.rb
