# This is a basic workflow to help you get started with Actions

name: Update

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Intall vhs && dependencies
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
          echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
          sudo apt-get update
          sudo apt-get install vhs ffmpeg
          sudo snap install ttyd --classic

      - name: Cleanup
        run: |
          rm -f renders/*.gif || true
          rm -f tapes/*.tape || true

      - name: Update Tapes
        run: ruby tape_updater.rb

      - name: Run VHS
        run: for i in ./tapes/*.tape; do vhs "$i"; done

      - name: Update README.md
        run: ruby readme_updater.rb

      - uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: Denny Mueller Mechanicus
          author_email: contact@dennymueller.io'
          default_author: user_info
          message: 'Update of themes'
          pathspec_error_handling: exitImmediately
